import argparse
from Bio.PDB import PDBIO, Select
from Bio.PDB.MMCIFParser import MMCIFParser
import os, subprocess
from rdkit import Chem
from rdkit.Chem import AllChem


class LigandSelect(Select):
    def accept_residue(self, residue):
        return residue.get_resname() == "LIG1"

class ProteinSelect(Select):
    def accept_residue(self, residue):
        return residue.get_resname() != "LIG1"

def split_complex(complex_cif, receptor='receptor.pdb', ligand='ligand.pdb'):
    #read cif file
    parser = MMCIFParser()
    structure = parser.get_structure("none", complex_cif)
    
    io = PDBIO()
    io.set_structure(structure)
    io.save(ligand, LigandSelect())
    io.save(receptor, ProteinSelect())

def prepare_receptor_input(receptor_pdb='receptor.pdb', receptor_mol2='receptor.mol2'):
  with open('receptor.tleap', 'w') as f:
    f.write('source leaprc.protein.ff19SB\n')
    f.write(f'rec = loadpdb {receptor_pdb}\n')
    f.write('charge rec\n')
    f.write(f'savemol2 rec {receptor_mol2} 0\n')
    f.write('quit\n')

def fix_ligand(ligand_file):
    prefix = ligand_file.split('.')[0]
    with open(ligand_file, 'r') as f:
        lines = f.readlines()
    with open(f'{prefix}_fixed.pdb', 'w') as f:
        for line in lines:
            line = line.replace('LIG1', 'LIG')
            f.write(line)
    return f'{prefix}_fixed.pdb'


def prepare_ligand(ligand='ligand.pdb', ligand_mol2='ligand.mol2', sanitize=True):
  # we replace LIG1 by LIG
  fixed_file = fix_ligand(ligand)

  # Using rdkit to add hydrogen atoms
  prefix = fixed_file.split('.')[0]
  rdkitmol = Chem.MolFromPDBFile(fixed_file, sanitize=sanitize)
  if rdkitmol is None:
    raise ValueError(f"Failed to read ligand PDB file: {ligand}")
  rdkitmol = Chem.AddHs(rdkitmol)
  AllChem.EmbedMolecule(rdkitmol)
  with Chem.SDWriter(f'{prefix}.sdf') as w:
    w.write(rdkitmol)

# Antechamber will compute charges for the sdf file generated by rdkit
  subprocess.run(['antechamber', '-i', f'{prefix}.sdf', '-fi', 'sdf', '-o',
                  f'{ligand_mol2}', '-fo', 'mol2', '-c', 'bcc', '-rn', 'LIG', 
                  '-at', 'sybyl', '-pf', 'y'])

def prepare_receptor(input_file, receptor='receptor.pdb'):
  subprocess.run(['tleap', '-f', f'{input_file}'])

def clean_up():
   os.system('rm -f receptor.tleap leap.log sqm.*')
   os.system('gzip *.mol2')

    
def prepare_complex(complex_cif, receptor='receptor.pdb', ligand='ligand.pdb'):

    assert os.path.exists(complex_cif), f"Input file {args.input} does not exist."
    
    split_complex(complex_cif, receptor=receptor, ligand=ligand)
    receptor_prefix = receptor.split('.')[0]
    prepare_receptor_input(receptor_pdb=receptor, receptor_mol2=f'{receptor_prefix}.mol2')
    prepare_receptor('receptor.tleap', receptor=receptor)
    
    if not os.path.exists(f'{receptor_prefix}.mol2'):
        raise FileNotFoundError(f"Failed to generate {receptor_prefix}.mol2")
    
    ligand_prefix = ligand.split('.')[0]
    prepare_ligand(ligand=ligand, ligand_mol2=f'{ligand_prefix}.mol2')

    if not os.path.exists(f'{ligand_prefix}.mol2'):
        raise FileNotFoundError(f"Failed to generate {ligand_prefix}.mol2")
    
    clean_up()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description ='Process cif files to generate mol2 files.')
    parser.add_argument('--input', type=str, help='Path to the input cif file')
    parser.add_argument('--receptor', type=str, default='receptor.pdb', help='Path to save the receptor pdb file')
    parser.add_argument('--ligand', type=str, default='ligand.pdb', help='Path to save the ligand pdb file') 
    args = parser.parse_args()
    print(args)

    prepare_complex(args.input, receptor=args.receptor, ligand=args.ligand)